name: GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
 
    - name: Install typescript
      run: npm install -g typescript
      
    - name: Install type defenitions
      run: npm i --save-dev @types/node

    - name: Prebuild
      run: node ./node_modules/typescript/bin/tsc --project tsconfig.prod.json

    - name: Build
      run: node20 build.js

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./src
        enable_jekyll: true
