name: npm audit

on:
  push:
    branches:
      - development

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Check code formatting
        run: npm run format

      - name: TypeScript type check
        run: tsc --noEmit

      - name: Run npm audit
        run: npm audit --audit-level=high
